---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ndtech-staging
  namespace: ndtech-staging
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/22ndtech/ndtech-flux-staging

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ndtech-staging
  namespace: ndtech-staging
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: ndtech-staging
  validation: client

