---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/tekton-pipeline
      sourceRef:
        kind: GitRepository
        name: ndtech-sapper
        namespace: ndtech
      interval: 1m
  values:
    replicaCount: 2
    auth:
      docker:
        url: https://hub.docker.com
