---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  interval: 10m0s
  path: ./releases/download/v1.1.0
  prune: true
  sourceRef:
    kind: GitRepository
    name: cert-manager
    namespace: flux-system
  validation: client
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/jetstack/cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/charts/cert-manager
      version: 0.0.1.5
      sourceRef:
        kind: GitRepository
        name: cert-manager
        namespace: cert-manager
      interval: 1m
  values:
    installCRDs: true
    image:
      tag: v1.1.0
    webhook:
      image:
        tag: v1.1.0
    cainjector:
      image:
        tag: v1.1.0