---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cdfoundation-tekton
  namespace: flux-system
spec:
  interval: 1m
  url: https://cdfoundation.github.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  interval: 5m
  chart:
    spec:
      chart: tekton
      version: '0.18.0'
      sourceRef:
        kind: HelmRepository
        name: cdfoundation-tekton
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2