---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cdfoundation-tekton
  namespace: flux-system
spec:
  interval: 1m
  url: https://cdfoundation.github.io/tekton-helm-chart/