---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ndtech-sapper
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/22ndtech/ndtech-sapper

